//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentFinder.Service.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualAd
    {
        public int AdId { get; set; }
        public decimal Price { get; set; }
        public int RentalTypeId { get; set; }
        public int RealtyTypeId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> Square { get; set; }
        public Nullable<int> Rooms { get; set; }
        public Nullable<int> Floor { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual RealtyType RealtyType { get; set; }
        public virtual RentalType RentalType { get; set; }
        public virtual Ad Ad { get; set; }
    }
}
