//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentFinder.Service.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActualAd
    {
        public int Id { get; set; }
        public string TempId { get; set; }
        public int ForeignId { get; set; }
        public string Link { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Rooms { get; set; }
    
        public virtual PhoneNumber PhoneNumber { get; set; }
    }
}
