//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentFinder.Service.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public int ActualAdId { get; set; }
        public string Number { get; set; }
    
        public virtual ActualAd ActualAd { get; set; }
    }
}
